export const EXTENSION_API_CONTRACT = {
  handshake: {
    method: 'POST',
    path: '/api/v1/extension/handshake',
    auth: 'user_jwt',
    request: { deviceId: 'string', publicKey: 'pem string' },
    response: {
      sessionId: 'string',
      deviceId: 'string',
      accessToken: 'string',
      expiresAt: 'iso8601',
      tokenType: 'Bearer',
    },
  },
  heartbeat: {
    method: 'POST',
    path: '/api/v1/extension/heartbeat',
    auth: 'extension_token + request_signature',
  },
  ackCommand: {
    method: 'POST',
    path: '/api/v1/extension/commands/ack',
    auth: 'extension_token + request_signature',
    payload: { commandId: 'string', status: 'string', result: 'object' },
  },
  pollTasks: {
    method: 'POST',
    path: '/api/v1/extension/tasks/poll',
    auth: 'extension_token + request_signature',
    payload: { limit: 'number' },
    response: {
      tasks: [
        {
          id: 'string',
          type: 'create_offer',
          orderId: 'string',
          tradeOperationId: 'string',
          idempotencyKey: 'string',
          payload: 'object',
          expiresAt: 'iso8601',
          attemptCount: 'number',
        },
      ],
    },
  },
  ackTask: {
    method: 'POST',
    path: '/api/v1/extension/tasks/ack',
    auth: 'extension_token + request_signature',
    payload: {
      taskId: 'string',
      result: 'ACK|NACK',
      reasonCode: 'string(optional)',
    },
  },
  reportTaskProgress: {
    method: 'POST',
    path: '/api/v1/extension/tasks/progress',
    auth: 'extension_token + request_signature',
    payload: {
      taskId: 'string',
      phase: 'ACKED|OFFER_DRAFTED|CONFIRM_PENDING|OFFER_SENT|OFFER_FAILED',
      idempotencyKey: 'string',
      reasonCode: 'string(optional)',
      offerId: 'string(optional)',
      details: 'object(optional)',
    },
    response: { ok: true, phase: 'string', terminal: 'boolean' },
  },
  submitTradeReference: {
    method: 'POST',
    path: '/api/v1/extension/orders/:orderId/trade-reference',
    auth: 'extension_token + request_signature',
    flags: ['ENABLE_EXTENSION_CHANNEL', 'ENABLE_EXTENSION_TRADE_REFERENCE'],
    payload: {
      orderId: 'string (must match path)',
      idempotencyKey: 'string (required)',
      offerId: 'string(optional)',
      tradeUrl: 'string(optional)',
    },
    response: {
      orderId: 'string',
      externalOfferId: 'string',
      applied: 'boolean',
      idempotent: 'boolean',
      disputed: 'boolean',
    },
  },
  rotateSession: {
    method: 'POST',
    path: '/api/v1/extension/session/rotate',
    auth: 'extension_token + request_signature',
  },
  revokeSession: {
    method: 'POST',
    path: '/api/v1/extension/session/revoke',
    auth: 'extension_token + request_signature',
  },
  signedEnvelope: {
    deviceId: 'string',
    nonce: 'string',
    timestampMs: 'number',
    ttlMs: 'number',
    payload: 'object',
    signature: 'base64 RSA-SHA256',
  },
  securityErrorCodes: [
    'EXTENSION_CHANNEL_DISABLED',
    'EXTENSION_SESSION_INVALID',
    'EXTENSION_SESSION_REVOKED',
    'EXTENSION_TOKEN_EXPIRED',
    'EXTENSION_SIGNATURE_INVALID',
    'EXTENSION_REPLAY_DETECTED',
    'EXTENSION_TIMESTAMP_INVALID',
    'EXTENSION_DEVICE_MISMATCH',
    'EXTENSION_TASK_INVALID_ACK',
    'EXTENSION_TASK_NOT_FOUND',
  ],
} as const;
