export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVENTORY_ASSET_NOT_AVAILABLE: 'INVENTORY_ASSET_NOT_AVAILABLE',
  INVENTORY_ASSET_NOT_TRADABLE: 'INVENTORY_ASSET_NOT_TRADABLE',
  INVENTORY_ASSET_TRADE_LOCKED: 'INVENTORY_ASSET_TRADE_LOCKED',
  LOT_ALREADY_EXISTS_FOR_ASSET: 'LOT_ALREADY_EXISTS_FOR_ASSET',
  SELLER_NOT_ACTIVE: 'SELLER_NOT_ACTIVE',
  LOT_NOT_FOUND: 'LOT_NOT_FOUND',
  INVENTORY_ASSET_NOT_FOUND: 'INVENTORY_ASSET_NOT_FOUND',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
