export const AUTH_PROVIDER = Symbol('AUTH_PROVIDER');
export const INVENTORY_PROVIDER = Symbol('INVENTORY_PROVIDER');
export const TRADE_PROVIDER = Symbol('TRADE_PROVIDER');
export const PAYMENT_PROVIDER = Symbol('PAYMENT_PROVIDER');
