export type SettlementBlockCode =
  | 'AUTO_SETTLEMENT_RISK_LIMIT'
  | 'SETTLEMENT_EVIDENCE_INVALID'
  | 'SETTLEMENT_REVIEW_REQUIRED'
  | 'SETTLEMENT_FINANCIAL_INCONSISTENCY'
  | 'SETTLEMENT_PROTECTION_ACTIVE'
  | 'STEAM_REVERSAL_DETECTED'
  | 'STEAM_RECHECK_UNAVAILABLE'
  | 'REAL_SETTLEMENT_DISABLED'
  | 'NOT_LIVE_MODE'
  | 'TRADE_NOT_CONFIRMED'
  | 'ORDER_NOT_TRADE_CONFIRMED'
  | 'MISSING_BUYER_STEAM_ID'
  | 'MISSING_SELLER_STEAM_ID'
  | 'BUYER_NOT_ALLOWLISTED'
  | 'SELLER_NOT_ALLOWLISTED'
  | 'ORDER_AMOUNT_EXCEEDS_LIMIT'
  | 'DAILY_ORDER_LIMIT'
  | 'DAILY_VOLUME_LIMIT';

export type SettlementGuardResult =
  | { allowed: true }
  | { allowed: false; code: SettlementBlockCode; reason: string };
