ALTER TYPE "TradeTaskExecutionPhase" ADD VALUE IF NOT EXISTS 'TRADE_PAGE_OPENED';
ALTER TYPE "TradeTaskExecutionPhase" ADD VALUE IF NOT EXISTS 'ITEM_SELECTED';
ALTER TYPE "TradeTaskExecutionPhase" ADD VALUE IF NOT EXISTS 'OFFER_SUBMITTED';
