export const ExtensionFlowLogCode = {
  ORDER_STARTED: 'EXT_FLOW_ORDER_STARTED',
  ORDER_COMPLETED: 'EXT_FLOW_ORDER_COMPLETED',
  ORDER_DISPUTED: 'EXT_FLOW_ORDER_DISPUTED',
  TASK_SUCCESS: 'EXT_FLOW_TASK_SUCCESS',
  TASK_FAILED: 'EXT_FLOW_TASK_FAILED',
  AUTH_ERROR: 'EXT_FLOW_AUTH_ERROR',
  VERIFY_MISMATCH: 'EXT_FLOW_VERIFY_MISMATCH',
  RATE_LIMITED: 'EXT_FLOW_RATE_LIMITED',
  ANTI_FRAUD_TRIGGERED: 'EXT_FLOW_ANTI_FRAUD_TRIGGERED',
  OPS_ALERT_FIRED: 'EXT_FLOW_OPS_ALERT_FIRED',
} as const;

export type ExtensionFlowLogCodeType =
  (typeof ExtensionFlowLogCode)[keyof typeof ExtensionFlowLogCode];

export const OpsAlertId = {
  TASK_FAILURE_SPIKE: 'TASK_FAILURE_SPIKE',
  EXTENSION_AUTH_ANOMALY: 'EXTENSION_AUTH_ANOMALY',
  VERIFY_MISMATCH_SPIKE: 'VERIFY_MISMATCH_SPIKE',
  COMPLETION_RATE_DROP: 'COMPLETION_RATE_DROP',
  DISPUTE_RATE_SPIKE: 'DISPUTE_RATE_SPIKE',
  ANTI_FRAUD_VELOCITY: 'ANTI_FRAUD_VELOCITY',
} as const;

export type OpsAlertIdType = (typeof OpsAlertId)[keyof typeof OpsAlertId];
